### ISSUE TITLE
Skygrid Chest loot settings

### ISSUE THREAD

**Issue by Lakrii** [BentoBoxWorld/SkyGrid#16]
So I've just installed skygrid on the server and saw that there's barely anything on the chests to loot.. is there a way to configure so the chests come with more items? or is it something you still need to add?

**Comment by Lakrii** [comment]
Also should add a command where it resets the chests that's been placed in the world (not by players) so new items has added so we don't have that problem where people take the stuff and leave an empty chest for someone else to come and have their heart shattered :D

**Comment by tastybento** [comment]
Thanks for the prompt. I added some extra config items:

```
world:
  chest-fill:
    # Chest fill setting. 1 = normal, 0 = nothing, 1+ for more items
    overworld: 10
    # Nether chest fill setting
    nether: 10
    # The End chest fill setting
    end: 10
```

That'll fill them up nicely.

In regards to refilling - it's not really an option right now because the chests are filled when blocks are generated.
