### ISSUE TITLE
New SkyGrid Island Generation Corrupts Worlds and Crashes Server

### ISSUE THREAD

**Issue by mercurialmusic** [BentoBoxWorld/SkyGrid#40]
**Description**
New SkyGrid island and general new chunk generation corrupts existing worlds in which generation is attempted. This is, I'm sure, entirely due to the changes from Spigot not too long ago, but even with the fixes in BBox 1.11.1 and the Spigot changes we have not seen substantial improvement in SkyGrid -- the others seem to be fine. Now any time a new player creates an island the server crashes. Someone created a new nether island and crash, nether world corrupted, then recently had the same happen in the main SkyGrid world. I don't really expect that a fix for this would come soon, but wanted to put this here all the same. Happy to share anything else. Thanks!

**Server Information:**
 - Database being used: JSON
 - OS: Ubuntu 18.04, Core i9, 64GB RAM
 - Java Version: Java 8
- Running: SPIGOT 1.15.2 (CraftBukkit version git-Spigot-6de3d4b-fc24934)
- BentoBox version: 1.11.1
- Loaded Game Worlds: AcidIsland_world (AcidIsland): Overworld, Nether, The End, BSkyBlock_world (BSkyBlock): Overworld, Nether, The End
- Loaded Addons: 
    - AcidIsland 1.11.0 (ENABLED)
    - BSkyBlock 1.11.0 (ENABLED)
    - Challenges 0.8.0 (ENABLED)
    - DimensionalTrees 1.6.0 (ENABLED)
    - Level 1.9.3 (ENABLED)
    - Limits 1.9.2 (ENABLED)
    - Warps 1.9.0 (ENABLED)

**Comment by mrfloris** [comment]
Confirmed, we now have players come online trying to crash the server. I've uninstalled the world Skygrid. 

You can see in my .txt i was able to reproduce it by logging in and teleporting to the location of the user that triggered the crash. I visually saw the world, and started falling, and boom, server shutdown.

[skygrid_server_crash.txt](https://github.com/BentoBoxWorld/SkyGrid/files/4321392/skygrid_server_crash.txt)

**Comment by tastybento** [comment]
I suspect you guys upgraded from an older version of SkyGrid to the latest? If so, can you share your config.yml file (just zip it and drag and drop to this ticket.)

**Comment by mercurialmusic** [comment]
I mean I upgraded from the version immediately before.. I generally keep it updated as they come out. 

GitHub doesn't seem to allow uploads of .yml so I pasted it here: https://gist.github.com/mercurialmusic/033445e400efa80c1542c7d33644da51

I think the only thing we changed was the number of spawners.

**Comment by tastybento** [comment]
Thanks. I found the problem. In the latest version chest items can be customized, but you have nothing in those lists because they were not in the previous version and the default is none. The addon is crashing because I'm asking it to pick a random number between 0 and 0 (the length of the list). Duh. I'll fix. 

Quick work around. Change this part of your config:
```
  chest-items:
    # Chest items will be taken randomly from this list. All items have an equal chance.
    overworld: []
    nether: []
    end: []
```
to the default (or customize):
```
  # Chest items will be taken randomly from this list. All items have an equal chance.
  chest-items:
    overworld:
    - ACTIVATOR_RAIL
    - ANVIL
    - APPLE
    - ARMOR_STAND
    - ARROW
    - BAKED_POTATO
    - BAMBOO_SAPLING
    - BARREL
    - BAT_SPAWN_EGG
    - BEACON
    - BEEF
    - BEETROOT_SEEDS
    - BEETROOT_SOUP
    - BELL
    - BLACK_BANNER
    - BLACK_BED
    - BLACK_DYE
    - BLAST_FURNACE
    - BLAZE_ROD
    - BLUE_BANNER
    - BLUE_BED
    - BLUE_DYE
    - BLUE_ICE
    - BLUE_WOOL
    - BONE
    - BONE_BLOCK
    - BONE_MEAL
    - BOOK
    - BOOKSHELF
    - BOW
    - BOWL
    - BREAD
    - BREWING_STAND
    - BRICK
    - BRICK_WALL
    - BRICKS
    - BROWN_BANNER
    - BROWN_BED
    - BROWN_DYE
    - BROWN_MUSHROOM
    - BROWN_WOOL
    - BUCKET
    - CACTUS
    - CAKE
    - CAMPFIRE
    - CARROT
    - CARROT_ON_A_STICK
    - CARTOGRAPHY_TABLE
    - CARVED_PUMPKIN
    - CAT_SPAWN_EGG
    - CAULDRON
    - CAVE_SPIDER_SPAWN_EGG
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - CHARCOAL
    - CHEST_MINECART
    - CHICKEN
    - CHICKEN_SPAWN_EGG
    - CHISELED_RED_SANDSTONE
    - CHISELED_SANDSTONE
    - CHISELED_STONE_BRICKS
    - CLAY
    - CLAY_BALL
    - CLOCK
    - COAL
    - COAL_BLOCK
    - COAL_ORE
    - COARSE_DIRT
    - COCOA
    - COCOA_BEANS
    - COD
    - COD_BUCKET
    - COD_SPAWN_EGG
    - COMPARATOR
    - COMPASS
    - COMPOSTER
    - CONDUIT
    - COOKED_BEEF
    - COOKED_CHICKEN
    - COOKED_COD
    - COOKED_MUTTON
    - COOKED_PORKCHOP
    - COOKED_RABBIT
    - COOKED_SALMON
    - COOKIE
    - CORNFLOWER
    - COW_SPAWN_EGG
    - CRAFTING_TABLE
    - CREEPER_BANNER_PATTERN
    - CREEPER_SPAWN_EGG
    - CROSSBOW
    - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - CYAN_BANNER
    - CYAN_BED
    - CYAN_DYE
    - CYAN_WOOL
    - DARK_PRISMARINE
    - DAYLIGHT_DETECTOR
    - DETECTOR_RAIL
    - DIAMOND
    - DIAMOND_AXE
    - DIAMOND_BLOCK
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_LEGGINGS
    - DIAMOND_ORE
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - DISPENSER
    - DOLPHIN_SPAWN_EGG
    - DONKEY_SPAWN_EGG
    - DRIED_KELP
    - DRIED_KELP_BLOCK
    - DROPPER
    - DROWNED_SPAWN_EGG
    - EGG
    - ELDER_GUARDIAN_SPAWN_EGG
    - EMERALD
    - EMERALD_BLOCK
    - EMERALD_ORE
    - ENCHANTED_BOOK
    - ENCHANTED_GOLDEN_APPLE
    - ENCHANTING_TABLE
    - ENDER_PEARL
    - EVOKER_SPAWN_EGG
    - EXPERIENCE_BOTTLE
    - FEATHER
    - FERMENTED_SPIDER_EYE
    - FERN
    - FIRE
    - FIRE_CHARGE
    - FIREWORK_ROCKET
    - FIREWORK_STAR
    - FISHING_ROD
    - FLETCHING_TABLE
    - FLINT
    - FLINT_AND_STEEL
    - FLOWER_BANNER_PATTERN
    - FLOWER_POT
    - FOX_SPAWN_EGG
    - FURNACE
    - FURNACE_MINECART
    - GHAST_SPAWN_EGG
    - GHAST_TEAR
    - GLISTERING_MELON_SLICE
    - GLOBE_BANNER_PATTERN
    - GLOWSTONE
    - GLOWSTONE_DUST
    - GOLD_BLOCK
    - GOLD_INGOT
    - GOLD_NUGGET
    - GOLD_ORE
    - GOLDEN_APPLE
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CARROT
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - GRAVEL
    - GRAY_BANNER
    - GRAY_BED
    - GRAY_DYE
    - GREEN_BANNER
    - GREEN_BED
    - GREEN_DYE
    - GRINDSTONE
    - GUARDIAN_SPAWN_EGG
    - GUNPOWDER
    - HAY_BLOCK
    - HEART_OF_THE_SEA
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - HOPPER
    - HOPPER_MINECART
    - HORSE_SPAWN_EGG
    - HUSK_SPAWN_EGG
    - ICE
    - INK_SAC
    - IRON_AXE
    - IRON_BARS
    - IRON_BLOCK
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_DOOR
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_INGOT
    - IRON_LEGGINGS
    - IRON_NUGGET
    - IRON_ORE
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - IRON_TRAPDOOR
    - ITEM_FRAME
    - JACK_O_LANTERN
    - JUKEBOX
    - KELP
    - KELP_PLANT
    - LADDER
    - LANTERN
    - LAPIS_BLOCK
    - LAPIS_LAZULI
    - LAPIS_ORE
    - LARGE_FERN
    - LAVA_BUCKET
    - LEAD
    - LEATHER
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - LECTERN
    - LEVER
    - LIGHT_BLUE_BANNER
    - LIGHT_BLUE_BED
    - LIGHT_BLUE_DYE
    - LIGHT_GRAY_BANNER
    - LIGHT_GRAY_BED
    - LIGHT_GRAY_DYE
    - LIGHT_GRAY_WOOL
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - LILAC
    - LILY_OF_THE_VALLEY
    - LILY_PAD
    - LIME_BANNER
    - LIME_BED
    - LIME_CARPET
    - LIME_DYE
    - LIME_WOOL
    - LLAMA_SPAWN_EGG
    - LOOM
    - MAGENTA_BANNER
    - MAGENTA_BED
    - MAGENTA_DYE
    - MAGENTA_WOOL
    - MAGMA_BLOCK
    - MAGMA_CREAM
    - MAGMA_CUBE_SPAWN_EGG
    - MAP
    - MELON
    - MELON_SEEDS
    - MELON_SLICE
    - MILK_BUCKET
    - MINECART
    - MOJANG_BANNER_PATTERN
    - MOOSHROOM_SPAWN_EGG
    - MULE_SPAWN_EGG
    - MUSHROOM_STEW
    - MUSIC_DISC_11
    - MUSIC_DISC_13
    - MUSIC_DISC_BLOCKS
    - MUSIC_DISC_CAT
    - MUSIC_DISC_CHIRP
    - MUSIC_DISC_FAR
    - MUSIC_DISC_MALL
    - MUSIC_DISC_MELLOHI
    - MUSIC_DISC_STAL
    - MUSIC_DISC_STRAD
    - MUSIC_DISC_WAIT
    - MUSIC_DISC_WARD
    - MUTTON
    - MYCELIUM
    - NAME_TAG
    - NAUTILUS_SHELL
    - NOTE_BLOCK
    - OBSERVER
    - OBSIDIAN
    - OCELOT_SPAWN_EGG
    - ORANGE_BANNER
    - ORANGE_BED
    - ORANGE_DYE
    - ORANGE_TULIP
    - ORANGE_WOOL
    - OXEYE_DAISY
    - PACKED_ICE
    - PAINTING
    - PANDA_SPAWN_EGG
    - PAPER
    - PARROT_SPAWN_EGG
    - PEONY
    - PETRIFIED_OAK_SLAB
    - PHANTOM_MEMBRANE
    - PHANTOM_SPAWN_EGG
    - PIG_SPAWN_EGG
    - PILLAGER_SPAWN_EGG
    - PINK_BANNER
    - PINK_BED
    - PINK_DYE
    - PINK_TULIP
    - PINK_WOOL
    - PISTON
    - PODZOL
    - POISONOUS_POTATO
    - POLAR_BEAR_SPAWN_EGG
    - POPPY
    - PORKCHOP
    - POTATO
    - POTATOES
    - POTTED_ACACIA_SAPLING
    - POTTED_ALLIUM
    - POTTED_AZURE_BLUET
    - POTTED_BAMBOO
    - POTTED_BIRCH_SAPLING
    - POTTED_BLUE_ORCHID
    - POTTED_BROWN_MUSHROOM
    - POTTED_CACTUS
    - POTTED_CORNFLOWER
    - POTTED_DANDELION
    - POTTED_DARK_OAK_SAPLING
    - POTTED_DEAD_BUSH
    - POTTED_FERN
    - POTTED_JUNGLE_SAPLING
    - POTTED_LILY_OF_THE_VALLEY
    - POTTED_OAK_SAPLING
    - POTTED_ORANGE_TULIP
    - POTTED_OXEYE_DAISY
    - POTTED_PINK_TULIP
    - POTTED_POPPY
    - POTTED_RED_MUSHROOM
    - POTTED_RED_TULIP
    - POTTED_SPRUCE_SAPLING
    - POTTED_WHITE_TULIP
    - POTTED_WITHER_ROSE
    - POWERED_RAIL
    - PRISMARINE
    - PUFFERFISH
    - PUFFERFISH_BUCKET
    - PUFFERFISH_SPAWN_EGG
    - PUMPKIN
    - PUMPKIN_PIE
    - PUMPKIN_SEEDS
    - PURPLE_BANNER
    - PURPLE_BED
    - PURPLE_DYE
    - PURPLE_WOOL
    - RABBIT
    - RABBIT_FOOT
    - RABBIT_HIDE
    - RABBIT_SPAWN_EGG
    - RABBIT_STEW
    - RAIL
    - RAVAGER_SPAWN_EGG
    - RED_BANNER
    - RED_BED
    - RED_DYE
    - RED_MUSHROOM
    - RED_MUSHROOM_BLOCK
    - RED_SAND
    - RED_SANDSTONE
    - RED_TULIP
    - RED_WOOL
    - REDSTONE
    - REDSTONE_BLOCK
    - REDSTONE_LAMP
    - REDSTONE_ORE
    - REDSTONE_TORCH
    - REPEATER
    - ROSE_BUSH
    - SADDLE
    - SALMON
    - SALMON_BUCKET
    - SALMON_SPAWN_EGG
    - SAND
    - SANDSTONE
    - SCAFFOLDING
    - SCUTE
    - SEA_LANTERN
    - SEA_PICKLE
    - SEAGRASS
    - SHEARS
    - SHEEP_SPAWN_EGG
    - SHIELD
    - SILVERFISH_SPAWN_EGG
    - SKELETON_HORSE_SPAWN_EGG
    - SKELETON_SPAWN_EGG
    - SKULL_BANNER_PATTERN
    - SLIME_BALL
    - SLIME_BLOCK
    - SLIME_SPAWN_EGG
    - SMITHING_TABLE
    - SMOKER
    - SNOW_BLOCK
    - SNOWBALL
    - SOUL_SAND
    - SPECTRAL_ARROW
    - SPIDER_EYE
    - SPIDER_SPAWN_EGG
    - SPONGE
    - SQUID_SPAWN_EGG
    - STICK
    - STICKY_PISTON
    - STONECUTTER
    - STRAY_SPAWN_EGG
    - STRING
    - SUGAR
    - SUGAR_CANE
    - SUNFLOWER
    - SWEET_BERRIES
    - SWEET_BERRY_BUSH
    - TERRACOTTA
    - TNT
    - TNT_MINECART
    - TORCH
    - TOTEM_OF_UNDYING
    - TRADER_LLAMA_SPAWN_EGG
    - TRAPPED_CHEST
    - TRIDENT
    - TRIPWIRE
    - TRIPWIRE_HOOK
    - TROPICAL_FISH_BUCKET
    - TROPICAL_FISH_SPAWN_EGG
    - TURTLE_EGG
    - TURTLE_HELMET
    - TURTLE_SPAWN_EGG
    - VEX_SPAWN_EGG
    - VILLAGER_SPAWN_EGG
    - VINDICATOR_SPAWN_EGG
    - VINE
    - WALL_TORCH
    - WANDERING_TRADER_SPAWN_EGG
    - WATER_BUCKET
    - WHEAT
    - WHEAT_SEEDS
    - WHITE_BANNER
    - WHITE_BED
    - WHITE_DYE
    - WHITE_TULIP
    - WHITE_WOOL
    - WITCH_SPAWN_EGG
    - WOLF_SPAWN_EGG
    - WRITABLE_BOOK
    - YELLOW_BANNER
    - YELLOW_BED
    - YELLOW_DYE
    - YELLOW_GLAZED_TERRACOTTA
    - YELLOW_WOOL
    - ZOMBIE_SPAWN_EGG
    - ZOMBIE_VILLAGER_SPAWN_EGG
    nether:
    - BLAZE_SPAWN_EGG
    - CHISELED_QUARTZ_BLOCK
    - DIAMOND_HORSE_ARMOR
    - ELYTRA
    - ENDER_EYE
    - NETHER_BRICK
    - NETHER_BRICK_FENCE
    - NETHER_BRICK_SLAB
    - NETHER_BRICK_STAIRS
    - NETHER_BRICK_WALL
    - NETHER_BRICKS
    - NETHER_PORTAL
    - NETHER_QUARTZ_ORE
    - NETHER_STAR
    - NETHER_WART
    - NETHER_WART_BLOCK
    - NETHERRACK
    - QUARTZ
    - QUARTZ_BLOCK
    - QUARTZ_PILLAR
    - QUARTZ_SLAB
    - QUARTZ_STAIRS
    - RED_NETHER_BRICK_SLAB
    - RED_NETHER_BRICK_STAIRS
    - RED_NETHER_BRICK_WALL
    - RED_NETHER_BRICKS
    - WITHER_ROSE
    - WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SPAWN_EGG
    - ZOMBIE_HORSE_SPAWN_EGG
    - ZOMBIE_PIGMAN_SPAWN_EGG
    end:
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CHORUS_FLOWER
    - CHORUS_FRUIT
    - CHORUS_PLANT
    - CYAN_SHULKER_BOX
    - DRAGON_BREATH
    - END_CRYSTAL
    - END_ROD
    - END_STONE
    - ENDERMAN_SPAWN_EGG
    - LIGHT_BLUE_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - POPPED_CHORUS_FRUIT
    - PURPLE_SHULKER_BOX
    - PURPUR_BLOCK
    - PURPUR_PILLAR
    - PURPUR_SLAB
    - PURPUR_STAIRS
    - RED_SHULKER_BOX
    - SHULKER_BOX
    - SHULKER_SHELL
    - SHULKER_SPAWN_EGG
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
```
